### ISSUE TITLE
[BUG} Error when sending formatted message

### ISSUE THREAD

**Issue by GGORG0** [ad2017gd/DiscordRichText#3]
![image](https://sharx.host/i/raw/5p8_0Vs)

Canary 106485 (02153ef) Host 0.0.131 Linux 64-Bit (5.10.82-1-Lts)
![image](http://sharx.host/i/raw/CCt0VjE)
(running on powercord + bdCompat)

**Comment by ad2017gd** [comment]
I think this is just something that can be fixed with a try catch or an if, since some mutations are not add mutations.

Can you check if this affects the functionality?

**Comment by ad2017gd** [comment]
I think this should be fixed. Please reopen if not.
